config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  resources :departments do
    resources :items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :destroy, :update]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(departments_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def update
    if @department.update(departments_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to department_path
  end

  def edit
    render partial: "form"
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def departments_params
    params.require(:department).permit(:stores, :floor)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path(@department)
  end

  private

    def item_params
      params.require(:item).permit(:name, :price, :description)
    end

    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1> <%= @department.id ? "Edit Department" : "Create Department" %> </h1>

<%= form_for @department do |f| %>

<%= f.label :stores %>
<%= f.text_field :stores %>

<%= f.label :floor %>
<%= f.text_field :floor %>

<%= f.submit %>

<% end %>

app/views/departments/index.html.erb
<h1> Departments Index </h1>

<%= link_to 'Create a new department', new_department_path %>

<ul>
  <% @departments.each do |department| %>
    <li> <%= link_to department.stores, department %> </li>
    <% end %>
</ul>

app/views/departments/show.html.erb
<h1> <%= @department.stores %> </h1>
<hr />
<p> Items </p>

<%= link_to 'View Items', department_items_path(@department) %>
<br />
<%= link_to 'Edit Department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete Department', @department, method: :delete %> 

app/views/items/_form.html.erb
<h1> <%= @item.id ? "Edit Item" : "Create Item" %> </h1>

<%= form_for [@department, @item] do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :price %>
<%= f.text_field :price %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.submit %>

<% end %>

app/views/items/index.html.erb
<h1> <%= @department.stores%> Items </h1>
<%= link_to 'Create a new item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li> <%= link_to item.name, [@department, item] %> </li>
    <% end %>
</ul>

app/views/items/show.html.erb
<h1> <%= @department.stores %> </h1>

<p>Item name: <%= @item.name %> </p>
<p>Price: $ <%= @item.price %> </p>
<p> Description: <%= @item.description %> </p>


<%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
<br />
<%= link_to 'Delete Item', [@department, @item], method: :delete %>

app/views/layouts/_navbar.html.erb
<%= link_to 'View All Departments', departments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>